START TRANSACTION;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS riders;

DROP TABLE IF EXISTS restaurant;

DROP TABLE IF EXISTS menu_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS ratings;

COMMIT;